### ISSUE TITLE
Low pass pi filter capacitor

### ISSUE THREAD

**Issue by BerenChang** [yoctometric/pressure-mat#1]
Hey I wonder is c19 and c20 really 4.7 mF capacitors? I am trying to replicate your project. Those capacitors are really big and the pico board probably won’t fit on top of it. Does it make sense to have 4.7 uF capacitors instead? Thank you!

**Comment by evlar416** [comment]
Hi, yes they were actually 4.7mF in order to reach the propper cutoff frequency for the filter. We found some low frequency noise on the power supply when using an oscilloscope so the filter was designed to reduce that.
